#!/bin/bash
AOTRITON_INSTALL_FROM_SOURCE=0 \
  USE_FLASH_ATTENTION=0 USE_MEM_EFF_ATTENTION=0 \
  USE_CUDA=OFF \
  USE_ROCM=ON \
  DEBUG=1 \
  python \
  external-builds/pytorch/build_prod_wheels.py \
  build \
  --output-dir=$HOME/py-out
